version: "3"

services:
  app:
    build:
      context: .
    ports:
    - "8000:8000"
    #volume that is used to update change we make
    #to our project in our docker image
    volumes:
    - ./app:/app
    command: >
      sh -C "python manage.py runserver 0.0.0.0:8000"

